{
 "title": "阿里云成本分摊统计",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "阿里云主账号个项目成本分摊2018-08",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='仙境传说';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='节奏大爆炸';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='元气偶像季';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='横扫千军';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='CDN';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='LeanCloud';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='XDAPP';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='运维';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='心动办公室';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='口水三国';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='TAPDB';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-08` where tagKey='XDCOM';"
    }
   ]
  },
  {
   "title": "阿里云主账号个项目成本分摊2018-07",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='仙境传说';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='节奏大爆炸';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='元气偶像季';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='横扫千军';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='CDN';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='LeanCloud';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='XDAPP';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='运维';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='心动办公室';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='口水三国';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='TAPDB';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-07` where tagKey='XDCOM';"
    }
   ]
  },
  {
   "title": "阿里云主账号个项目成本分摊2018-06",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='仙境传说';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='节奏大爆炸';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='元气偶像季';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='横扫千军';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='CDN';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='LeanCloud';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='XDAPP';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='运维';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='心动办公室';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='口水三国';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='TAPDB';"
    },
    {
     "rawSql": "select sum(pretaxAmount) as '实际付款',tagKey as '项目' from `2018-06` where tagKey='XDCOM';"
    }
   ]
  }
 ]
}