{
 "title": "FortiGate 1200D",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Device Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU & Mem & Disk",
     "type": "graph",
     "description": "- 12142: cpu\n- 12143: mem\n- 12144: disk",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "target": "centreon.metrics.12142" },
      { "target": "centreon.metrics.12143" },
      { "target": "centreon.metrics.12144" }
     ]
    }
   ]
  },
  {
   "title": "NetScaler流量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "vlan520",
     "type": "graph",
     "description": "- 12140: traffic_out\n- 12141: traffic_in",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.12140" },
      { "target": "centreon.metrics.12141" }
     ]
    }
   ]
  },
  {
   "title": "神仙道流量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "vlan203",
     "type": "graph",
     "description": "- 14226: traffic_out\n- 14227: traffic_in",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.14226" },
      { "target": "centreon.metrics.14227" }
     ]
    }
   ]
  }
 ]
}