{
 "title": "横扫千军业务监控",
 "tags": [
  "业务监控",
  "横扫千军"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "在线人数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "online",
     "select": [
      [
       { "params": [ "count_all" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hsqj" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "阿里云SLB01",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zef5vsmhsc28kyqwelnv" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "阿里云SLB02",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze6807ehjpangmv16iy5" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "measurement": "netscaler",
     "select": [
      [
       { "params": [ "v" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "10.3.2.1" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "lb_gw-m-ro.xd.com-tcp5021" },
      { "condition": "AND", "key": "port", "operator": "=", "value": "161" }
     ]
    }
   ]
  },
  {
   "title": "SLB1_rta",
   "type": "singlestat",
   "description": "47.94.121.226",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22984" }
   ]
  },
  {
   "title": "SLB2_rta",
   "type": "singlestat",
   "description": "182.92.245.83",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22984" }
   ]
  },
  {
   "title": "专线1-rta",
   "type": "singlestat",
   "description": "pc-25d9cs5d1",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.11224" }
   ]
  },
  {
   "title": "专线2-rta",
   "type": "singlestat",
   "description": "pc-2zecuy3h0mo96lwja6l0v",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.3326" }
   ]
  },
  {
   "title": "高防华北BGP-rta",
   "type": "singlestat",
   "description": "47.95.51.4",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.19235" }
   ]
  },
  {
   "title": "高防联通-loss",
   "type": "singlestat",
   "description": "218.60.112.18",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.16009" }
   ]
  },
  {
   "title": "阿里云节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "RO_SLB01_后端健康节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zef5vsmhsc28kyqwelnv" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "物理节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "rawSql": "SELECT count(*) as UP from host where monitor='on'",
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "SLB1_loss",
   "type": "singlestat",
   "description": "47.94.121.226",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22985" }
   ]
  },
  {
   "title": "SLB2_loss",
   "type": "singlestat",
   "description": "182.92.245.83",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "centreon.metrics.22983" }
   ]
  },
  {
   "title": "专线1-loss",
   "type": "singlestat",
   "description": "pc-25d9cs5d1",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.11223" }
   ]
  },
  {
   "title": "专线2-loss",
   "type": "singlestat",
   "description": "pc-2zecuy3h0mo96lwja6l0v",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.3325" }
   ]
  },
  {
   "title": "高防华北BGP-loss",
   "type": "singlestat",
   "description": "47.95.51.4",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.19234" }
   ]
  },
  {
   "title": "高防电信-loss",
   "type": "singlestat",
   "description": "180.97.161.119",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.16007" }
   ]
  },
  {
   "title": "国内_阿里云入口_流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "横扫千军_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zef5vsmhsc28kyqwelnv" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "横扫千军_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficTX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zef5vsmhsc28kyqwelnv" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "横扫千军_国内_SLB02_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze6807ehjpangmv16iy5" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "横扫千军_国内_SLB02_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze6807ehjpangmv16iy5" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "鹏博士-总出入口",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.905, '鹏博士-总出口-入流量')"
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.906, '鹏博士-总出口-出流量')"
    }
   ]
  },
  {
   "title": "mysql_global_status_qps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x005 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9105\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x007 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9106\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x008 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9107\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x011 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9108\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x013 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9109\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x015 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9110\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x017 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9111\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x019 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9112\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x021 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9113\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x023 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.56.3:9114\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb 46x025 QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "Master commands(DML+rollback)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"rollback\",instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rollback",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\",instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\",instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\",instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.56.3:9104\",job=\"hsqj_database\"}[5m])",
     "legendFormat": "select"
    }
   ]
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hsqj" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hsqj" }
     ]
    }
   ]
  }
 ]
}