{
 "title": "HillStone",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "NetScaler流量", "type": "row", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "B01-NetScaler",
   "type": "graph",
   "description": "- 911: traffic_in\n- 912: traffic_out",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.911" },
    { "target": "centreon.metrics.912" }
   ]
  },
  {
   "title": "F01-NetScaler",
   "type": "graph",
   "description": "- 909: traffic_in\n- 910: traffic_out",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.909" },
    { "target": "centreon.metrics.910" }
   ]
  },
  {
   "title": "神仙道流量",
   "type": "row",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "F03_HillStone-G5150",
     "type": "graph",
     "description": "- 919: traffic_in\n- 920: traffic_out",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.919" },
      { "target": "centreon.metrics.920" }
     ]
    }
   ]
  },
  {
   "title": "盛世三国2流量",
   "type": "row",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "F03_HillStone-G5150",
     "type": "graph",
     "description": "- 917: traffic_in\n- 918: traffic_out",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.917" },
      { "target": "centreon.metrics.918" }
     ]
    }
   ]
  },
  {
   "title": "天下网游流量",
   "type": "row",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "B01_HillStone-G5150",
     "type": "graph",
     "description": "- 915: traffic_in\n- 916: traffic_out",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.915" },
      { "target": "centreon.metrics.916" }
     ]
    }
   ]
  }
 ]
}