{
 "title": "IDC出口流量",
 "tags": [
  "出口流量",
  "4900",
  "基础网络"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "鹏博士数据中心", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "D05-Core-1 Te1/1",
   "type": "graph",
   "description": "- 901: traffic_in\n- 902: traffic_out",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.901" },
    { "target": "centreon.metrics.902" }
   ]
  },
  {
   "title": "D05-Core-1 Te1/2",
   "type": "graph",
   "description": "- 903: traffic_in\n- 904: traffic_out",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.903" },
    { "target": "centreon.metrics.904" }
   ]
  },
  {
   "title": "D05-Core-2 Te1/1",
   "type": "graph",
   "description": "- 905: traffic_in\n- 906: traffic_out",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.905" },
    { "target": "centreon.metrics.906" }
   ]
  },
  {
   "title": "D05-Core-2 Te1/2",
   "type": "graph",
   "description": "- 907: traffic_in\n- 908: traffic_out",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.907" },
    { "target": "centreon.metrics.908" }
   ]
  },
  {
   "title": "D05-Core-2 Te1/8 - 脉创",
   "type": "graph",
   "description": "- 27204: traffic_in\n- 27205: traffic_out",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.27204" },
    { "target": "centreon.metrics.27205" }
   ]
  }
 ]
}