{
 "title": "将神国服业务监控",
 "tags": [ "业务监控" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "在线人数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "online",
     "select": [
      [
       { "params": [ "count_all" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "jiangshen" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "SLB_loss",
   "type": "singlestat",
   "description": "47.95.68.227",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27409" }
   ]
  },
  {
   "title": "SLB_TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "js_gateway01连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeorlzkxhi4j1dzbqvfa" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "阿里云入口_流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "js_gateway01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeorlzkxhi4j1dzbqvfa" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    },
    {
     "alias": "js_gateway01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeorlzkxhi4j1dzbqvfa" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "gateway01_后端节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "gateway01_后端节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeorlzkxhi4j1dzbqvfa" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "阿里云节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "js_gateway01_后端健康节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeorlzkxhi4j1dzbqvfa" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "SLB_rta",
   "type": "singlestat",
   "description": "47.95.68.227",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27410" }
   ]
  },
  { "title": "RDS Monitor (shrd001-shrd008)", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "content": "# title" },
  {
   "title": "001_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze51qj8v67ikh98t" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "002_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zep71663mpol7408" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "003_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze60sd949w7i7539" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "004_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze2291kh78u9497q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "005_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7zp0917182ws63" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "006_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze8p3y17lxt9eb64" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "007_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zeir6n1ih07x1m8a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "008_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zefd93p004ke01tc" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "001_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze51qj8v67ikh98t" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "002_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zep71663mpol7408" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "003_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze60sd949w7i7539" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "004_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze2291kh78u9497q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "005_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7zp0917182ws63" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "006_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze8p3y17lxt9eb64" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "007_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zeir6n1ih07x1m8a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "008_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zefd93p004ke01tc" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "001_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze51qj8v67ikh98t" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "002_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zep71663mpol7408" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "003_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze60sd949w7i7539" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "004_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze2291kh78u9497q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "005_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7zp0917182ws63" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "006_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze8p3y17lxt9eb64" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "007_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zeir6n1ih07x1m8a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "008_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zefd93p004ke01tc" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "001_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze51qj8v67ikh98t" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "002_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zep71663mpol7408" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "003_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze60sd949w7i7539" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "004_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze2291kh78u9497q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "005_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7zp0917182ws63" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "006_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze8p3y17lxt9eb64" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "007_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zeir6n1ih07x1m8a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "008_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zefd93p004ke01tc" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "001_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze51qj8v67ikh98t" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "002_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zep71663mpol7408" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "003_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze60sd949w7i7539" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "004_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze2291kh78u9497q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "005_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7zp0917182ws63" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "006_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze8p3y17lxt9eb64" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "007_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zeir6n1ih07x1m8a" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "008_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zefd93p004ke01tc" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1424626875116556" }
     ]
    }
   ]
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "jiangshen" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js" }
     ]
    }
   ]
  }
 ]
}