{
 "title": "监控总屏",
 "tags": [
  "总览",
  "运维"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>监控总览</span>\n</div>"
  },
  {
   "title": "服务状态监控",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "DNS 状态",
     "measurement": "service",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n",
     "tags": [
      { "key": "project", "operator": "=", "value": "core" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "daning-dns" }
     ]
    },
    {
     "alias": "DHCP 状态",
     "measurement": "service",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "core" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "daning-dhcp" }
     ]
    }
   ]
  },
  {
   "title": "DHCP status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "service",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "core" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "daning-dhcp" }
     ]
    }
   ]
  },
  { "title": "报警列表", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 } },
  {
   "title": "DNS status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "service",
     "select": [
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "core" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "daning-dns" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>基础流量监控</span>\n</div>"
  },
  {
   "title": "鹏博士-总出入口",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.905, '鹏博士-总出口-入流量')"
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.906, '鹏博士-总出口-出流量')"
    }
   ]
  },
  {
   "title": "阿里-鹏博士-专线",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.925, '专线1-入流量')"
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.926, '专线1-出流量')"
    },
    {
     "target": "alias(centreon.metrics.14586, '专线2-入流量')"
    },
    {
     "target": "alias(centreon.metrics.14587, '专线2-出流量')"
    }
   ]
  },
  {
   "title": "远近VPN-BJ流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(centreon.metrics.27417, 'BJ-traffic in')"
    },
    {
     "target": "alias(centreon.metrics.27418, 'BJ-traffic out')"
    }
   ]
  },
  {
   "title": "远近VPN-HK流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(centreon.metrics.27424, 'HK-traffic in')"
    },
    {
     "target": "alias(centreon.metrics.27425, 'HK-traffic out')"
    }
   ]
  },
  {
   "title": "中港高速通道流量监控",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "流入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_express_connect",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "ri-2zeat9wsqjin70komumm2" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ReceiveBandwidth" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "流出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_express_connect",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "ri-2zeat9wsqjin70komumm2" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "TransportedBandwidth" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  }
 ]
}