{
 "title": "Mysql NDB  性能测试",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "mysql_global_status_ndb_api_bytes_sent_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_sent_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_sent_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_sent_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_bytes_received_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_received_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_received_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_bytes_received_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_event_data_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_data_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_data_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_data_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_event_nondata_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_nondata_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_nondata_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_event_nondata_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_pk_op_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_pk_op_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_pk_op_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_pk_op_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_read_row_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_read_row_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_read_row_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_read_row_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_table_scan_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_table_scan_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_table_scan_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_table_scan_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_trans_local_read_row_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_trans_local_read_row_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_trans_local_read_row_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_trans_local_read_row_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_wait_meta_request_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_meta_request_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_meta_request_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_meta_request_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_wait_exec_complete_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_exec_complete_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_exec_complete_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_exec_complete_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_ndb_api_wait_nanos_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_nanos_count{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_nanos_count{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_ndb_api_wait_nanos_count{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_connections{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_connections{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_connections{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_connections{instance=\"10.1.52.26:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_qps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.52.26:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_select",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.52.26:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_droptable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"drop_table\",instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"drop_table\",instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"drop_table\",instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_slow_queries",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_slow_queries{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "mysql_global_status_threads_connected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "mysql_global_status_threads_connected{instance=\"10.1.52.21:9104\",job=\"mydql_ndb_test\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "mysql_global_status_threads_connected{instance=\"10.1.52.22:9104\",job=\"mydql_ndb_test\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "mysql_global_status_threads_connected{instance=\"10.1.52.23:9104\",job=\"mydql_ndb_test\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "mysql_global_status_threads_connected{instance=\"10.1.52.26:9104\",job=\"mydql_ndb_test\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  }
 ]
}