{
 "title": "鹏博士Ping监控汇总",
 "description": "ping",
 "tags": [ "基础网络" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ping_百度_loss",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.18805" }
   ]
  },
  {
   "title": "ping_114DNS_loss",
   "type": "graph",
   "description": "114.114.114.114",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.18803" }
   ]
  },
  {
   "title": "ping_QQ_loss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.22987" }
   ]
  },
  {
   "title": "ping_阿里高防华北BGP_loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.19234" }
   ]
  },
  {
   "title": "ping_阿里BGP测试_loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.25165" }
   ]
  },
  {
   "title": "ping_鹏博士4900_loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "centreon.metrics.25150" }
   ]
  },
  {
   "title": "ping_阿里ecs_loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(centreon.metrics.25169, 'falcon01')"
    },
    {
     "target": "alias(centreon.metrics.25171, 'falcon02')"
    },
    {
     "target": "alias(centreon.metrics.25167, 'falcon03')"
    }
   ]
  },
  {
   "title": "ping_脉创_loss",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(centreon.metrics.25152, '江苏常州电信')"
    },
    {
     "target": "alias(centreon.metrics.25156, '江苏常州联通')"
    },
    {
     "target": "alias(centreon.metrics.25154, '江苏常州移动')"
    },
    {
     "target": "alias(centreon.metrics.25158, '脉创75.2')"
    },
    {
     "target": "alias(centreon.metrics.25160, '脉创75.24')"
    },
    {
     "target": "alias(centreon.metrics.25163, '阿里云青岛bgp')"
    }
   ]
  }
 ]
}