{
 "title": "RO海外Fluentd流量",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "阿里云香港ECS", "type": "row", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "47.91.244.240",
   "type": "graph",
   "description": "- 16642: traffic_in\n- 16643: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16642" },
    { "target": "centreon.metrics.16643" }
   ]
  },
  {
   "title": "47.91.250.159",
   "type": "graph",
   "description": "- 16644: traffic_in\n- 16645: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16644" },
    { "target": "centreon.metrics.16645" }
   ]
  },
  {
   "title": "47.94.250.194",
   "type": "graph",
   "description": "- 16646: traffic_in\n- 16647: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16646" },
    { "target": "centreon.metrics.16647" }
   ]
  },
  {
   "title": "47.52.103.145",
   "type": "graph",
   "description": "- 16648: traffic_in\n- 16649: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16648" },
    { "target": "centreon.metrics.16649" }
   ]
  },
  { "title": "阿里云北京ECS", "type": "row", "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "47.94.250.194",
   "type": "graph",
   "description": "- 16614: traffic_in\n- 16615: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16614" },
    { "target": "centreon.metrics.16615" }
   ]
  },
  {
   "title": "47.94.228.31",
   "type": "graph",
   "description": "- 16616: traffic_in\n- 16617: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16616" },
    { "target": "centreon.metrics.16617" }
   ]
  },
  {
   "title": "47.94.234.94",
   "type": "graph",
   "description": "- 16618: traffic_in\n- 16619: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16618" },
    { "target": "centreon.metrics.16619" }
   ]
  },
  {
   "title": "47.94.222.192",
   "type": "graph",
   "description": "- 16620: traffic_in\n- 16621: traffic_out",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.16620" },
    { "target": "centreon.metrics.16621" }
   ]
  }
 ]
}