{
 "title": "仙境传说-系统监控",
 "description": "cpu,load,mem,network,uptime,diskio",
 "tags": [
  "系统监控",
  "仙境传说"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "HostName",
    "query": "show tag values with key = \"host\";"
   }
  ]
 },
 "panels": [
  {
   "title": "$HostName UP Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName CPU idle%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Free Total Memery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName / - Disk Used Percent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName /data - Disk Used Percent",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/data" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Load_1min%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Load_5min%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Load_15min%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName 目录：/   DiskIO-bytes_per_sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "目录：/ read_bytes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    },
    {
     "alias": "目录：/ write_bytes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "$HostName 目录：/  DiskIO-Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "locale", "label": "IO request per seconds" }
   ],
   "targets": [
    {
     "alias": "目录：/ reads per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    },
    {
     "alias": "目录：/ writes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sda" }
     ]
    }
   ]
  },
  {
   "title": "$HostName 目录：/data  DiskIO-bytes_per_sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "目录：/data read_bytes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "目录：/data write_bytes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "$HostName 目录：/data  DiskIO-Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "locale", "label": "IO requests per seconds" }
   ],
   "targets": [
    {
     "alias": "目录：/data reads per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    },
    {
     "alias": "目录：/data writes per sec",
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "sdb" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Load 1 min",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "alias": "Load 5 min",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "alias": "Load 15 min",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Memery",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "swap_free" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    },
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "swap_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HostName Bond0 Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes per second" }
   ],
   "targets": [
    {
     "alias": "net.bytes_recv",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "bond0" }
     ]
    },
    {
     "alias": "net.bytes_send",
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$HostName$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "bond0" }
     ]
    }
   ]
  }
 ]
}