{
 "title": "仙境传说业务监控",
 "tags": [
  "业务监控",
  "仙境传说"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "在线人数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "online",
     "select": [
      [
       { "params": [ "count_all" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ro" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "鹏博士5021",
     "measurement": "netscaler",
     "select": [
      [
       { "params": [ "vsvrEstablishedConn" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "10.3.2.1" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "lb_gw-m-ro.xd.com-tcp5021" },
      { "condition": "AND", "key": "port", "operator": "=", "value": "161" }
     ]
    },
    {
     "alias": "鹏博士5022",
     "measurement": "netscaler",
     "select": [
      [
       { "params": [ "vsvrEstablishedConn" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "10.3.2.1" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "lb_gw-m-ro.xd.com-tcp5022" },
      { "condition": "AND", "key": "port", "operator": "=", "value": "161" }
     ]
    },
    {
     "alias": "阿里云SLB01",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "阿里云SLB02",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zehtfflpsdaa9aj20it0" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "阿里海外02",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zeui1iiryp8o2ws437yb" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "阿里海外01",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze1cernquqmp1wibjbol" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "SLB1_rta",
   "type": "singlestat",
   "description": "47.94.121.226",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22984" }
   ]
  },
  {
   "title": "SLB2_rta",
   "type": "singlestat",
   "description": "182.92.245.83",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22984" }
   ]
  },
  {
   "title": "专线1-rta",
   "type": "singlestat",
   "description": "pc-25d9cs5d1",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.11224" }
   ]
  },
  {
   "title": "专线2-rta",
   "type": "singlestat",
   "description": "pc-2zecuy3h0mo96lwja6l0v",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.3326" }
   ]
  },
  {
   "title": "高防华北BGP-rta",
   "type": "singlestat",
   "description": "47.95.51.4",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.19235" }
   ]
  },
  {
   "title": "高防电信-loss",
   "type": "singlestat",
   "description": "180.97.161.119",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.16007" }
   ]
  },
  {
   "title": "阿里云节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "RO_SLB01_后端健康节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "物理节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "rawSql": "SELECT count(*) as UP from host where status=3",
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "SLB1_loss",
   "type": "singlestat",
   "description": "47.94.121.226",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.22985" }
   ]
  },
  {
   "title": "SLB2_loss",
   "type": "singlestat",
   "description": "182.92.245.83",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "target": "centreon.metrics.22983" }
   ]
  },
  {
   "title": "专线1-loss",
   "type": "singlestat",
   "description": "pc-25d9cs5d1",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.11223" }
   ]
  },
  {
   "title": "专线2-loss",
   "type": "singlestat",
   "description": "pc-2zecuy3h0mo96lwja6l0v",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.3325" }
   ]
  },
  {
   "title": "高防联通-loss",
   "type": "singlestat",
   "description": "218.60.112.18",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.16009" }
   ]
  },
  {
   "title": "高防华北BGP-loss",
   "type": "singlestat",
   "description": "47.95.51.4",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.19234" }
   ]
  },
  {
   "title": "国内_阿里云入口_流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficTX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB02_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zehtfflpsdaa9aj20it0" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "alias": "仙境传说_国内_SLB02_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zehtfflpsdaa9aj20it0" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "阿里-鹏博士-专线",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.925, '专线1-入流量')"
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.926, '专线1-出流量')"
    },
    {
     "target": "alias(centreon.metrics.14586, '专线2-入流量')"
    },
    {
     "target": "alias(centreon.metrics.14587, '专线2-出流量')"
    }
   ]
  },
  {
   "title": "鹏博士-总出入口",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.905, '鹏博士-总出口-入流量')"
    },
    {
     "alias": "仙境传说_国内_SLB01_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "alias(centreon.metrics.906, '鹏博士-总出口-出流量')"
    }
   ]
  },
  {
   "title": "mysql_global_status_qps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_queries{instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Mariadb Master QPS",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "Master Load 1min",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "RO_SLB01_后端健康节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ],
     "target": "centreon.metrics.8627"
    }
   ]
  },
  {
   "title": "Master max_used_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Master threads_connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Master Mem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 17 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "RO_SLB01_后端健康节点",
     "expr": "mysql_global_status_memory_used{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "Master innodb_buffer_pool_read_requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Master innodb_data_fsyncs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_fsyncs{instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Master Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 20 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "alias": "RO_SLB01_后端健康节点",
     "expr": "mysql_global_status_uptime{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    }
   ]
  },
  {
   "title": "Master innodb_buffer_pool_write_requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 20 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_write_requests{instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "mysql_global_status_slow_queries",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "Master commands(DML+rollback)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "仙境传说_国内_SLB01_入流量",
     "expr": "rate(mysql_global_status_commands_total{command=\"rollback\",instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "rollback",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze87urpyzo1xutorxfru" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1578441730305797" }
     ]
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\",instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "legendFormat": "update"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\",instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "legendFormat": "insert"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\",instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\",instance=\"10.1.61.22:9104\",job=\"ro_database\"}[5m])",
     "legendFormat": "select"
    }
   ]
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ro" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 27 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ro" }
     ]
    }
   ]
  }
 ]
}