{
 "title": "心动项目备份归档",
 "tags": [
  "运维",
  "备份归档"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>心动项目备份归档</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "content": "<h3 align=\"center\">香肠派对</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "content": "#### 详细说明：\n\n- 备份模式： `rds`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `*-*-* 00:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 05:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 4 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xcpd" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xcpd" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "content": "<h3 align=\"center\">最终王冠</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "content": "#### 详细说明：\n\n- 备份模式： `rds`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `*-*-* 00:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 05:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "zzwg" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "zzwg" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "<h3 align=\"center\">心灵战争</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "content": "#### 详细说明：\n\n- 备份模式： `rds`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `*-*-* 00:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 05:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 23 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "iw" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "iw" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "content": "<h3 align=\"center\">核心设备备份配置文件备份</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "content": "#### 详细说明：\n\n- 备份模式： `tftp`\n- 备份设备： `42x003.xd.cn,archive.xindong.com`\n- 备份时间： `daily`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 00:00:00`"
  },
  {
   "title": "yunwei",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 32 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "yunwei" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
   "content": "<h3 align=\"center\">仙境传说</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper`\n- 备份设备： `51x001.xd.cn`\n- 备份时间： `prod:00,06,12,18:40:00`,`beta:00,06,12,18:20:00`,`trade:00,06,12,18:50:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 03:15:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 41 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ro" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 41 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ro" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "content": "<h3 align=\"center\">横冲直撞</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
   "content": "#### 详细说明：\n\n- 备份模式： `阿里 logical backup`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `每天 *-*-* 00:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 04:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 47 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hczz" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 47 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hczz" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "content": "<h3 align=\"center\">心动后台</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 54 },
   "content": "#### 详细说明：\n源库在日本AWS：52.196.53.77\n备份脚本在东京mariadb_slave节点：13.230.16.229\n\n- 备份模式： `mydumper`\n- 备份设备： `在东京mariadb_slave节点：13.230.16.229`\n- 备份时间： `每天 *-*-* 00:00:00`\n  \n\n- 归档模式：`东京S3`\n- 归档时间：`*-*-* 04:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 54 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xdapp" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 54 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xdapp" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "content": "<h3 align=\"center\">天天打波利</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 61 },
   "content": "#### 详细说明：\n\n- 备份模式： `阿里redis rdb备份`\n- 备份设备： `tomason@aliyun.com`\n- 备份时间： `每天  04:00-05:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 00:30:00`"
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 18, "w": 20, "x": 4, "y": 61 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "ttdbl" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "content": "<h3 align=\"center\">仙侠道</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 81 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `*-*-* 01:30:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 03:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 81 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xxd" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 81 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xxd" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
   "content": "<h3 align=\"center\">仙侠道2</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 92 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper`\n- 备份设备： `42x001.xd.cn`\n- 备份时间： `*-*-* 03:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 05:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 92 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xxd2" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 92 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "xxd2" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "content": "<h3 align=\"center\">神仙道</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 79, "w": 4, "x": 0, "y": 102 },
   "content": "#### 详细说明：\n\n- 备份模式： `mysql-binlog增量备份`\n- 备份设备： `42x004.xd.cn`\n- 备份时间： `every hour`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 01:30:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 78, "w": 10, "x": 4, "y": 102 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sxd-binlog" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 78, "w": 10, "x": 14, "y": 102 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sxd-binlog" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 181 },
   "content": "<h3 align=\"center\">神仙道每月全量</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 183 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper全量备份`\n- 备份设备： `core@42x002.xd.cn`\n- 备份时间： `每月1号 *-*-01 01:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`每月10号 *-*-10 04:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 183 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sxd-mydumper" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 183 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sxd-mydumper" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 188 },
   "content": "<h3 align=\"center\">将神国服</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 190 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper`\n- 备份设备： `42x001`\n- 备份时间： `每天 *-*-* 00:00:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`每天 *-*-* 05:00:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 190 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "jiangshen" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 190 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "js" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 196 },
   "content": "<h3 align=\"center\">横扫千军</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 198 },
   "content": "#### 详细说明：\n\n- 备份模式： `mydumper`\n- 备份设备： `46x003.xd.cn`\n- 备份时间： `*-*-* 01:30:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 02:31:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 198 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hsqj" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 198 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "hsqj" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 208 },
   "content": "<h3 align=\"center\">三国罗曼史</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 210 },
   "content": "#### 详细说明：\n\n- 备份模式： `阿里RDS mysqldump`\n- 备份设备： `alisglms`\n- 备份时间： `*-*-* 01:30:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 03:01:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 210 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sglms" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 210 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sglms" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 215 },
   "content": "<h3 align=\"center\">盛世三国</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 217 },
   "content": "#### 详细说明：\n\n- 备份模式： `阿里RDS mydumper`\n- 备份设备： `59.110.40.204`\n- 备份时间： `*-*-* 02:30:00`\n  \n\n- 归档模式：`S3`\n- 归档时间：`*-*-* 01:30:00`"
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 217 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sssg" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 217 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "sssg" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 230 },
   "content": "<h3 align=\"center\">mariabackup</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 232 },
   "content": "#### 详细说明：\n\n- 备份模式： `mariabackup`\n- 备份设备： `jk002`\n\n备份时间： \n- 正式服\n`every 2 hour`\n- 交易所\n`every hour`"
  },
  {
   "title": "仙境传说_正式服51x140",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "正式服140",
     "measurement": "mariabackup",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "rdsName", "operator": "=", "value": "gamedb_slave_140" }
     ]
    }
   ]
  },
  {
   "title": "仙境传说交易所51x070",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "交易所070",
     "measurement": "mariabackup",
     "select": [
      [
       { "params": [ "success" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "rdsName", "operator": "=", "value": "tradedb_slave_070" }
     ]
    }
   ]
  }
 ]
}