{
 "title": "心灵战争业务监控",
 "tags": [ "业务监控" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "在线人数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "online",
     "select": [
      [
       { "params": [ "count_all" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "iw" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "IW_SLB_loss",
   "type": "singlestat",
   "description": "59.110.95.21",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27732" }
   ]
  },
  {
   "title": "IW_SLB_2_loss",
   "type": "singlestat",
   "description": "39.107.217.27",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27734" }
   ]
  },
  {
   "title": "IW_SLB_TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "IW_SLB连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze15bak8gi82x2ext4bn" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "IW_SLB_2_TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "IW_SLB_2连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zetcq5w2pzle284ddum9" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "IW_SLB_后端健康节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IW_SLB_后端节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze15bak8gi82x2ext4bn" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "IW_SLB_2_后端健康节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IW_SLB_2_后端健康节点",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zetcq5w2pzle284ddum9" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "IW_SLB_rta",
   "type": "singlestat",
   "description": "59.110.95.21",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27733" }
   ]
  },
  {
   "title": "IW_SLB_2_rta",
   "type": "singlestat",
   "description": "39.107.217.27",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27735" }
   ]
  },
  {
   "title": "阿里云入口_IW_SLB_流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "IW_SLB_入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze15bak8gi82x2ext4bn" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    },
    {
     "alias": "IW_SLB_出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2ze15bak8gi82x2ext4bn" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "阿里云入口_IW_SLB_2_流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "IW_SLB_2入流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zetcq5w2pzle284ddum9" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    },
    {
     "alias": "IW_SLB_2出流量",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-2zetcq5w2pzle284ddum9" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "高防入口流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ]
  },
  {
   "title": "accdb-1_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze90e7063l1q4k51" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "gsdb-1(GS1-15)_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze750hmje067i4pf" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "gsdb-2(GS16-30)_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zesha7m428107l58" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "gsdb-3(GS31-45)_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7819c93ab127j7" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "reportdb-1_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "public-1(P1-3)_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zej2uqbn90q15s5x" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "iw" }
     ]
    }
   ]
  },
  {
   "title": "001_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze90e7063l1q4k51" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "002_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze750hmje067i4pf" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "003_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zesha7m428107l58" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "004_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7819c93ab127j7" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zej2uqbn90q15s5x" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "001_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze90e7063l1q4k51" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "002_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze750hmje067i4pf" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "003_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zesha7m428107l58" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "004_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7819c93ab127j7" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zej2uqbn90q15s5x" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "iw" }
     ]
    }
   ]
  },
  {
   "title": "001_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze90e7063l1q4k51" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "002_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze750hmje067i4pf" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "003_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zesha7m428107l58" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "004_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7819c93ab127j7" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zej2uqbn90q15s5x" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "001_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze90e7063l1q4k51" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "002_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze750hmje067i4pf" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "003_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2zesha7m428107l58" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "004_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze7819c93ab127j7" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  },
  {
   "title": "005_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-2ze467295k0b26g5d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1477918150824094" }
     ]
    }
   ]
  }
 ]
}