{
 "title": "专线流量(按VPC)",
 "description": "VPC流量划分",
 "tags": [
  "专线流量",
  "基础网络"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "阿里云VPC流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPC-XD-GAME_1012",
   "type": "graph",
   "description": "- 3597: traffic_in\n- 3598: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.3597" },
    { "target": "centreon.metrics.3598" }
   ]
  },
  {
   "title": "VPC-XD-GAME_1112",
   "type": "graph",
   "description": "- 14588: traffic_in\n- 14589: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.14588" },
    { "target": "centreon.metrics.14589" }
   ]
  },
  {
   "title": "VPC-XD-WEB_1011",
   "type": "graph",
   "description": "- 3458: traffic_in\n- 3459: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.3458" },
    { "target": "centreon.metrics.3459" }
   ]
  },
  {
   "title": "VPC-XD-WEB_1111",
   "type": "graph",
   "description": "- 14592: traffic_in\n- 14593: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.14592" },
    { "target": "centreon.metrics.14593" }
   ]
  },
  {
   "title": "VPC-XD-GF_1010",
   "type": "graph",
   "description": "- 4898: traffic_in\n- 4899: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.4898" },
    { "target": "centreon.metrics.4899" }
   ]
  },
  {
   "title": "VPC-XD-GF_1110",
   "type": "graph",
   "description": "- 14590: traffic_in\n- 14591: traffic_out",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.14590" },
    { "target": "centreon.metrics.14591" }
   ]
  },
  {
   "title": "AWS VPC流量",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "VPC-PBS-001",
     "type": "graph",
     "description": "- 11225: traffic_in\n- 11226: traffic_out",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      { "target": "centreon.metrics.11225" },
      { "target": "centreon.metrics.11226" }
     ]
    }
   ]
  }
 ]
}