{
 "title": "专线流量(按线路)",
 "tags": [
  "专线流量",
  "基础网络"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "专线流量", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "阿里云专线1流量（E3/47）",
   "type": "graph",
   "description": "925 traffic in\n926 traffic out",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.925" },
    { "target": "centreon.metrics.926" }
   ]
  },
  {
   "title": "阿里云专线2流量（E3/43）",
   "type": "graph",
   "description": "14586 traffic in\n14587 traffic out",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.14586" },
    { "target": "centreon.metrics.14587" }
   ]
  },
  {
   "title": "AWS专线流量（E4/47）",
   "type": "graph",
   "description": "923 traffic in\n924 traffic out",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "centreon.metrics.923" },
    { "target": "centreon.metrics.924" }
   ]
  }
 ]
}