{
 "title": "最终王冠业务监控",
 "tags": [ "业务监控" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "在线人数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "online",
     "select": [
      [
       { "params": [ "count_all" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "zzwg" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "标准SLB1_loss",
   "type": "singlestat",
   "description": "47.101.20.29",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27774" }
   ]
  },
  {
   "title": "高防SLB1_loss",
   "type": "singlestat",
   "description": "47.101.18.71",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27772" }
   ]
  },
  {
   "title": "标准域名SLB_TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "xd-lastcrown-SLB连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6naakjji1q9yrnz0u4r" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "备用-SLB连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6vu34ya5alegr576wma" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "高防域名SLB_TCP连接数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "高防SLB_连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf63f6runz2vrhk9lag2g" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "备用高防SLB_连接数",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6fjejmqnc7qnjasmnv6" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceActiveConnection" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "标准SLB1_后端健康节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "标准SLB1_后端节点",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6naakjji1q9yrnz0u4r" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "高防SLB1_后端健康节点",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "IW_SLB_2_后端健康节点",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf63f6runz2vrhk9lag2g" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "HeathyServerCount" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "标准SLB1_rta",
   "type": "singlestat",
   "description": "47.101.20.29",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27775" }
   ]
  },
  {
   "title": "高防SLB1_rta",
   "type": "singlestat",
   "description": "47.101.18.71",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    { "target": "centreon.metrics.27773" }
   ]
  },
  {
   "title": "阿里云入口_xd-lastcrown_SLB_流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "xd-lastcrown_SLB入流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6naakjji1q9yrnz0u4r" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "xd-lastcrown_SLB出流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6naakjji1q9yrnz0u4r" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "阿里云入口_备用SLB_流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "备用SLB_入流量",
     "measurement": "acs_slb_dashboard",
     "query": "SELECT mean(\"Average\") FROM \"acs_slb_dashboard\" WHERE (\"instanceId\" = 'lb-2ze87urpyzo1xutorxfru' AND \"metric\" = 'InstanceTrafficRX' AND \"regionId\" = 'cn-beijing' AND \"userId\" = '1578441730305797') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6vu34ya5alegr576wma" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "备用SLB_出流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6vu34ya5alegr576wma" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "高防入口流量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "高防01_入流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf63f6runz2vrhk9lag2g" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "高防01_出流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf63f6runz2vrhk9lag2g" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "备用高防_入流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6fjejmqnc7qnjasmnv6" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficRX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    },
    {
     "alias": "备用高防_出流量",
     "measurement": "acs_slb_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "lb-uf6fjejmqnc7qnjasmnv6" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "InstanceTrafficTX" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动登录_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf6adwe8i98hd65ze" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "心动2区4区_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf61lbio781t2w550" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "心动5-10区_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf683t45it239ha0m" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "心动1区3区_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf601gx4k5p02ax3y" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "渠道服DB_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf679vd8l00ng2v1q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "正式服DB_connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=\"10.1.61.22:9104\",job=\"ro_database\"}",
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" },
       { "params": [ "*40" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf66j8soe03btj48d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "ConnectionUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ],
     "target": "apps.backend.backend_02.counters.requests.count"
    }
   ]
  },
  {
   "title": "backup",
   "type": "table",
   "description": "备份",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "measurement": "backup",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "zzwg" }
     ]
    }
   ]
  },
  {
   "title": "心动登录_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf6adwe8i98hd65ze" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动2区4区_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf61lbio781t2w550" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动5-10区_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf683t45it239ha0m" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动1区3区_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf601gx4k5p02ax3y" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "渠道服DB_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf679vd8l00ng2v1q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "正式服DB_CPU(%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf66j8soe03btj48d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "CpuUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动登录_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf6adwe8i98hd65ze" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动2区4区_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf61lbio781t2w550" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动5-10区_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf683t45it239ha0m" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动1区3区_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf601gx4k5p02ax3y" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "渠道服DB_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf679vd8l00ng2v1q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "正式服DB_Mem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf66j8soe03btj48d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "MemoryUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "archive",
   "type": "table",
   "description": "归档",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "measurement": "archive",
     "select": [
      [
       { "params": [ "rdsname" ], "type": "field" }
      ],
      [
       { "params": [ "total" ], "type": "field" }
      ],
      [
       { "params": [ "success" ], "type": "field" }
      ],
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=", "value": "zzwg" }
     ]
    }
   ]
  },
  {
   "title": "心动登录_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf6adwe8i98hd65ze" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动2区4区_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf61lbio781t2w550" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动5-10区_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf683t45it239ha0m" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动1区3区_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf601gx4k5p02ax3y" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "渠道服DB_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf679vd8l00ng2v1q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "正式服DB_Disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf66j8soe03btj48d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "DiskUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动登录_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf6adwe8i98hd65ze" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动2区4区_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf61lbio781t2w550" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动5-10区_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf683t45it239ha0m" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "心动1区3区_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf601gx4k5p02ax3y" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "渠道服DB_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf679vd8l00ng2v1q" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  },
  {
   "title": "正式服DB_IOPS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "acs_rds_dashboard",
     "select": [
      [
       { "params": [ "Average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "instanceId", "operator": "=", "value": "rm-uf66j8soe03btj48d" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "IOPSUsage" },
      { "condition": "AND", "key": "regionId", "operator": "=", "value": "cn-beijing" },
      { "condition": "AND", "key": "userId", "operator": "=", "value": "1407058981274091" }
     ]
    }
   ]
  }
 ]
}